// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://visbbrkvzbajnpcstpza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpc2Jicmt2emJham5wY3N0cHphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4NzQ2MjUsImV4cCI6MjA1NDQ1MDYyNX0.o8d-f--hdbQQh4ANIpC990TPud1-GfyraUzJRVh2-sE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);